openapi: 3.1.0
info:
  title: Project Manager API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local Dev
tags:
  - name: Tasks
    description: Task-related endpoints
  - name: Teams
    description: Team-related endpoints
  - name: Team Members
    description: Team Members-related endpoints
  - name: Projects
    description: Project-related endpoints
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  #teams paths
  /api/teams:
    $ref: paths/teams.yaml
  /api/teams/{id}:
    $ref: paths/teamId.yaml
  /api/teams/{teamId}/members:
    $ref: paths/teamMember.yaml
  /api/teams/{teamId}/members/{userId}:
    $ref: paths/teamMemberId.yaml
  #tasks paths
  /api/tasks:
    $ref: paths/tasks.yaml
  /api/tasks/me:
    $ref: paths/tasksMe.yaml
  /api/tasks/{id}:
    $ref: paths/tasksById.yaml
  #projects paths
  /api/projects:
    $ref: paths/projects.yaml
  /api/projects/{id}:
    $ref: paths/projects-id.yaml
  #auth and users paths
  /auth/signup:
    $ref: paths/auth_signup.yaml
  /auth/login:
    $ref: paths/auth_login.yaml
  /users/me:
    $ref: paths/users_me.yaml
  /users:
    $ref: paths/users.yaml
  /users/{id}/role:
    $ref: paths/users_{id}_role.yaml
  /users/{id}:
    $ref: paths/users_{id}.yaml
  
